Repository test-fullautomation/robotframework-dbus, pull requests merged in 2023-06, with the labels that each got.

#6 +Add machenism for remote dbus test
  RobotFramework_DBus/common/__init__.py
  RobotFramework_DBus/common/priority_queue.py
  RobotFramework_DBus/common/register_keyword.py
  RobotFramework_DBus/common/scheduled_job.py
  RobotFramework_DBus/common/thread_safe_dict.py
  RobotFramework_DBus/common/utils.py
  RobotFramework_DBus/dbus_agent/dbus_client_agent.py
  RobotFramework_DBus/dbus_client.py
  RobotFramework_DBus/dbus_client_remote.py
  RobotFramework_DBus/dbus_manager.py
  RobotFramework_DBus/thread_safe_dict.py
Labels: enhancement, 0.9.0

#7 -Update documents and install scripts
  RobotFramework_DBus/RobotFramework_DBus.pdf
  RobotFramework_DBus/common/register_keyword.py
  RobotFramework_DBus/common/scheduled_job.py
  RobotFramework_DBus/dbus_agent/dbus_client_agent.py
  RobotFramework_DBus/dbus_client.py
  RobotFramework_DBus/dbus_client_remote.py
  RobotFramework_DBus/dbus_manager.py
  atest/server.py
  atest/test_dbus_examples.robot
  config/repository_config.json
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/Introduction.tex
  setup.py
Labels: documentation, enhancement, 0.9.0

#8 -Change the way to import version
  config/CRepositoryConfig.py
Labels: enhancement, 0.9.0

#9 Adapted date and company name
  README.rst
  RobotFramework_DBus/__init__.py
  RobotFramework_DBus/common/__init__.py
  RobotFramework_DBus/common/priority_queue.py
  RobotFramework_DBus/common/register_keyword.py
  RobotFramework_DBus/common/scheduled_job.py
  RobotFramework_DBus/common/thread_safe_dict.py
  RobotFramework_DBus/common/utils.py
  RobotFramework_DBus/dbus_agent/dbus_client_agent.py
  RobotFramework_DBus/dbus_client.py
  RobotFramework_DBus/dbus_client_remote.py
  RobotFramework_DBus/dbus_manager.py
  RobotFramework_DBus/version.py
  additions/CExtendedSetup.py
  additions/__init__.py
  atest/server.py
  atest/test_dbus_examples.robot
  config/CRepositoryConfig.py
  config/__init__.py
  dump_repository_config.py
  genpackagedoc.py
  packagedoc/additional_docs/Appendix.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.tex
  readme.rst2md.py
  setup.py
Labels: documentation, 0.9.0
